---
- name: Install Bottle
  pip: name=bottle

- name: Install requests
  pip: name=requests

- name: Upload Application
  copy: src=vAPI.py dest=/var/www/api/

- name: Start API
  shell: "/usr/bin/python /var/www/api/vAPI.py 2>&1 &"
