---
- name: Install Bottle
  pip: name=bottle

- name: Install requests
  pip: name=requests

- name: Upload Application
  copy: src=vAPI.py dest=/var/www/api/

- name: Upload supervisor config
  copy: src=vAPI.conf dest=/etc/supervisor/conf.d/

- name: Stop supervisord
  shell: killall supervisord
  args:
    sudo: yes
    sudo_user: vagrant

- name: Start supervisord
  shell: supervisord -c /etc/supervisor/supervisord.conf
  args:  
    sudo: yes
    sudo_user: vagrant
